try:
    print(x)

except:
    print("Error occured")

finally:
    print("Successful")